### ISSUE TITLE
Nginx 反向代理时报错 Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by ColdeZhang** [MCSManager/Website#5]
# 文档的反向代理没有问题  

按照文档的方式配置反向代理直接访问可以正常使用，mcsm安装肯定没有问题。

# 但是当我想将url变为 /mcsm 结尾的时候浏览器报错  

`Uncaught SyntaxError: Unexpected token '<'`  

> 我想将访问方式从http://domain.site 变为 http://domain.site/mcsm

这是我的nginx配置
```
location /mcsm/ {
	    proxy_http_version 1.1;
            proxy_pass http://127.0.0.1:25555/;  # 因为23333端口在兼容mcsm8 所以新面板使用的25555端口
            
            proxy_set_header Host $http_host/mcsm;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header REMOTE-HOST $remote_addr;
            
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            add_header X-Cache $upstream_cache_status;
            add_header Cache-Control no-cache;
            expires 12h;
}
```

# 查阅了一些资料后

 - 查阅了一些资料后发现问题可能与静态资源加载错误有关，但是无论我使用rewrite重写路径还是单独的location配置路径都无法解决问题；

**Comment by ColdeZhang** [comment]
我将index.html里所有的资源地址都换成了相对地址，现在静态资源都能正常加载了。
发现还需要请求一个api地址，所以我额外转发了一个/api/
```
location /api/ {
	    proxy_pass http://127.0.0.1:25555/api/;
	    proxy_http_version 1.1;
            proxy_set_header Host $host/mcsm/api;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header REMOTE-HOST $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            add_header X-Cache $upstream_cache_status;
            add_header Cache-Control no-cache;
            expires 12h;
            proxy_cache_bypass $http_upgrade;
}
```
但是发现获取token的时候还是不正常。

`GET http://domain.site/api/auth/?token= 403 (Forbidden)`

**Comment by Suwings** [comment]
token= 此参数如果为空的话，就代表 token 获取失败，不过刚刷新网页的刚出现几次这个错误是正常的，只要能正确显示网页和用户数据即可。

你可以更多的尝试一下，如果成功，欢迎回来反馈一下方案，共享一下。

**Comment by ColdeZhang** [comment]
好吧我解决问题了
> token获取失败仅仅是因为我密码输错了（丢人）

# 想要反代MCSM二级目录的步骤大概是

## 1.首先稍微修改一下源码

将web/public下的index.html种引用的所有css与js路径全部改为绝对路径，具体来收就是在最前面加上`.`。
比如：`/css/xxxxxx.css`修改为`./css/xxxxxx.css`

> 我尝试过在nginx中使用rewrite重写css与js文件的路径，但是这么做会影响到这个server中的其他web应用。从原理上来说http我们似乎没有办法告诉nginx哪些样式文件是属于那个应用的，所以可能无法直接通过设置nginx来解决这个问题。（我尝试过设置二级目录的root位置来实现这一效果，但是mcsm是基于nodejs开发的，好像这么设置并不管用，这一块触及到知识盲区了有懂得请踢我一脚）

## 2.在nginx中做如下配置
```
location /mcsm/ {
	    proxy_pass http://127.0.0.1:25555/;
            proxy_http_version 1.1;
	    # Web 端反向代理目标 
            # 一些必要的 HTTP Header 设置
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header REMOTE-HOST $remote_addr;
            # 必须的 Websocket 支持
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            add_header X-Cache $upstream_cache_status;
            add_header Cache-Control no-cache;
            expires 12h;
            proxy_cache_bypass $http_upgrade;
}

location /api/ {
	    proxy_pass http://127.0.0.1:25555/api/;
            proxy_http_version 1.1;
            # 一些必要的 HTTP Header 设置
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header REMOTE-HOST $remote_addr;
            # 必须的 Websocket 支持
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            add_header X-Cache $upstream_cache_status;
            add_header Cache-Control no-cache;
            expires 12h;
            proxy_cache_bypass $http_upgrade;
}
```

这里是贴的我的配置，需要注意一下:
1. 由于我的23333端口正在运营MCSM8，所以此处我修改了MCSM9的端口为25555，你需要按照你的实际情况设置；
2. 除了代理`/mcsm/`外还需要代理`/api/`，因为MCSM页面上的信息是完全依赖这个地址获取的，所以需要将这个地址上的流量代理到内网地址上的`/api/`。后续如果想使用api获取服务器信息也需要用到这个地址，所以这也是必要的（不过如果你的其他网站应用也需要使用这个地址的话......）；
3. 这里没有贴出守护进程的代理，那部分就按照官方文档的教程做就行；
4. 除此之外，你会发现图片不能正常显示，因为图片也是用相对地址引入的因此你也需要修改那部分源码（或者建议将图片全部替换为图床地址）。

# 一点小小的建议

能不能在后续的版本中将代码中的文件地址替换为绝对地址 TAT；

**Comment by ColdeZhang** [comment]
> 谢谢你的贡献，很不错的经验文章，我会考虑将你这篇文章添加到readme或者官方文档中。
> 
> 另外，你的第四点 `除此之外，你会发现图片不能正常显示，因为图片也是用相对地址引入的因此你也需要修改那部分源码（或者建议将图片全部替换为图床地址）。`
> 
> 我觉得你可以尝试在 index.html 中加入 `<base>` 标签来进行处理，应该不复杂，如果你愿意尝试并且有结果的话欢迎继续告诉我。
> 
> 用法：https://www.w3school.com.cn/tags/tag_base.asp

谢谢指路，效果很好👍
